const countryEmojiMap = {
    "United States": "🇺🇸",
    "South Africa": "🇿🇦",
    "Scotland": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    "Uzbekistan": "🇺🇿",
    "Haiti": "🇭🇹",
    "DR Congo": "🇨🇩",
    "Norway": "🇳🇴",
    "Saudi Arabia": "🇸🇦",
    "Sweden": "🇸🇪",
    "Ecuador": "🇪🇨",
    "Senegal": "🇸🇳",
    "New Zealand": "🇳🇿",
    "Curaçao": "🇨🇼",
    "Curacao": "🇨🇼",
    "Australia": "🇦🇺",
    "Bosnia and Herzegovina": "🇧🇦",
    "Egypt": "🇪🇬",
    "Iraq": "🇮🇶",
    "Uruguay": "🇺🇾",
    "South Korea": "🇰🇷",
    "Czech Republic": "🇨🇿",
    "Ghana": "🇬🇭",
    "Jordan": "🇯🇴",
    "Cape Verde": "🇨🇻",
    "Canada": "🇨🇦",
    "Tunisia": "🇹🇳",
    "Croatia": "🇭🇷",
    "Ivory Coast": "🇨🇮",
    "Austria": "🇦🇹",
    "Iran": "🇮🇷",
    "Panama": "🇵🇦",
    "Qatar": "🇶🇦",
    "Morocco": "🇲🇦",
    "Switzerland": "🇨🇭",
    "Algeria": "🇩🇿",
    "Turkey": "🇹🇷",
    "Paraguay": "🇵🇾",
    "Spain": "🇪🇸",
    "France": "🇫🇷",
    "Argentina": "🇦🇷",
    "Portugal": "🇵🇹",
    "Brazil": "🇧🇷",
    "Germany": "🇩🇪",
    "England": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    "Italy": "🇮🇹",
    "Netherlands": "🇳🇱",
    "Belgium": "🇧🇪",
    "Denmark": "🇩🇰",
    "Colombia": "🇨🇴",
    "Mexico": "🇲🇽",
    "Japan": "🇯🇵",
    "Nigeria": "🇳🇬",
    "Cameroon": "🇨🇲",
    "Chile": "🇨🇱",
    "Peru": "🇵🇪",
    "Poland": "🇵🇱",
    "Serbia": "🇷🇸",
    "Wales": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
    "Northern Ireland": "🇬🇧"
};

export const getCountryEmoji = (name) => {
    if (!name) return '🌍';
    return countryEmojiMap[name] || '🌍';
};
